# Generated by Django 3.0.6 on 2020-05-18 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20200518_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='format_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='original_language_books', to='tracking.FormatDetail'),
        ),
    ]
