# Generated by Django 3.0.6 on 2020-05-18 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_book_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='formatdetail',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('first_name',)},
        ),
        migrations.AlterModelOptions(
            name='prize',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ('name',)},
        ),
    ]
