# Generated by Django 3.0.6 on 2020-05-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_auto_20200518_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.CharField(choices=[('audio', 'Audio'), ('cartaceo', 'Cartaceo'), ('ebook', 'E-Book')], max_length=1024),
        ),
        migrations.AlterField(
            model_name='book',
            name='prizes',
            field=models.ManyToManyField(to='tracking.Prize'),
        ),
        migrations.AlterField(
            model_name='book',
            name='suggested_by',
            field=models.CharField(blank=True, choices=[('ale', 'Ale'), ('amici', 'Amici'), ('autonoma', 'Ricerca autonoma'), ('autore-piaciuto', 'Autore piaciuto'), ('caso', 'Il Caso'), ('circolo', 'Il Circolo di lettura'), ('facebook', 'Facebook'), ('internazionale', "L'Internazionale"), ('lettore-piaciuto', 'Lettore piaciuto'), ('murgia', 'La Murgia'), ('pinterest', 'Pinterest'), ('post', 'Il Post'), ('reddit', 'Reddit'), ('tv', 'TV'), ('venerdi', 'Il Venerdi')], max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('altro', 'Altro'), ('donna', 'Donna'), ('uomo', 'Uomo')], max_length=1024),
        ),
    ]
