# Generated by Django 3.0.6 on 2020-05-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_auto_20200518_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='prizes',
            field=models.ManyToManyField(blank=True, to='tracking.Prize'),
        ),
    ]
