# Generated by Django 3.0.6 on 2020-06-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_auto_20200606_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='file',
            new_name='image',
        ),
    ]
