# Generated by Django 3.0.6 on 2021-12-28 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_auto_20200902_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='illustrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='illustrator_books', to='tracking.Person'),
        ),
    ]
