# Generated by Django 3.0.6 on 2021-12-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0015_auto_20211228_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
