# Generated by Django 3.0.6 on 2021-12-28 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0017_auto_20211228_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='book_genre',
        ),
    ]
