# Generated by Django 3.0.6 on 2021-12-28 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0018_auto_20211228_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_genre',
            new_name='genre',
        ),
        migrations.AlterField(
            model_name='book',
            name='sub_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_genre_books', to='tracking.Genre'),
        ),
    ]
